_prototypes: # Some useful defaults
  Excitatory neuron: &exc
    sign: 1
    n: 200 # ~1% of Potjans2014-cm L2/3
    p: -0.1 # Hand-tuned
    noise_N: 2000   # Potjans2014-cm, Table 5
    noise_rate: 8   # Potjans2014-cm, Table 5
    noise_weight: 2e-3 # Hand-tuned
  Inhibitory neuron: &inh
    sign: -1
    n: 56 # ~1% of Potjans2014-cm L2/3
    p: 0
    noise_N: 1850   # Potjans2014-cm, Table 5
    noise_rate: 8   # Potjans2014-cm, Table 5
    noise_weight: 2e-3 # Hand-tuned
    th_ampl: 0.05
  Synapse defaults: &synapse
    spatial: True
    density: 0.5
    delay: 1e-3
  Excitatory to excitatory synapse: &ee
    <<: *synapse
    STDP_frac: 1.
    A_p: 1.5 # Hand-tuned
    A_d: 0.5 # Hand-tuned
  Local e-to-e: &local_ee
    <<: *ee
  Local e-to-i: &local_ei
    <<: *synapse
  Local i-to-e: &local_ie
    <<: *synapse
  Local i-to-i: &local_ii
    <<: *synapse

populations:
  Thal:
    n: 10
    rate: 0
    targets:
      Ex1:
        <<: *synapse
        delay: 0
      In1:
        <<: *synapse
        delay: 0
  Ex1:
    <<: *exc
    targets:
      Ex1: *local_ee
      In1: *local_ei
  In1:
    <<: *inh
    targets:
      Ex1: *local_ie
      In1: *local_ii
