_prototypes: # Some useful defaults
  Excitatory neuron: &exc
    sign: 1
    n: 200 # ~1% of Potjans2014-cm L2/3
    p: -0.1 # Hand-tuned
    noise_N: 2000   # Potjans2014-cm, Table 5
    noise_rate: 8   # Potjans2014-cm, Table 5
    noise_weight: 2e-3 # Hand-tuned
    th_ampl: 0.05
  Inhibitory neuron: &inh
    sign: -1
    n: 56 # ~1% of Potjans2014-cm L2/3
    p: 0
    noise_N: 1850   # Potjans2014-cm, Table 5
    noise_rate: 8   # Potjans2014-cm, Table 5
    noise_weight: 2e-3 # Hand-tuned
  Synapse defaults: &synapse
    spatial: True
    density: 0.5
    delay: 1e-3
  Excitatory to excitatory synapse: &ee
    <<: *synapse
    STDP_frac: 1.
    A_p: 0.2 # Hand-tuned
    A_d: 0.2 # Hand-tuned
  Local e-to-e: &local_ee
    <<: *ee
  Local e-to-i: &local_ei
    <<: *synapse
  Local i-to-e: &local_ie
    <<: *synapse
  Local i-to-i: &local_ii
    <<: *synapse

input:
  n_channels: 1
  populations:
    Thal:
      n: 20
      channel: 0
      targets:
        L1:Exc:
          <<: *synapse
        L1:Inh:
          <<: *synapse
areas:
  L1:
    populations:
      Exc:
        <<: *exc
        targets:
          Exc: *local_ee
          Inh: *local_ei
      Inh:
        <<: *inh
        targets:
          Exc: *local_ie
          Inh: *local_ii
