_prototypes: # Some useful defaults
  Excitatory neuron: &exc
    sign: 1
    n: 200 # ~1% of Potjans2014-cm L2/3
    p: -0.1 # Hand-tuned
    noise_N: 2000   # Potjans2014-cm, Table 5
    noise_rate: 8   # Potjans2014-cm, Table 5
    noise_weight: 3e-3 # Hand-tuned
  Inhibitory neuron: &inh
    sign: -1
    n: 56 # ~1% of Potjans2014-cm L2/3
    p: 0
    noise_N: 1850   # Potjans2014-cm, Table 5
    noise_rate: 8   # Potjans2014-cm, Table 5
    noise_weight: 3e-3 # Hand-tuned
  Excitatory to excitatory synapse: &ee
    A_p: 0.1 # Hand-tuned
    A_d: 0.15 # Hand-tuned
  Local e-to-e: &local_ee
    <<: *ee
    density: 0.1 # L2/3, Potjans2014-cm
  Local e-to-i: &local_ei
    density: 0.14 # L2/3, Potjans2014-cm
  Local i-to-e: &local_ie
    density: 0.17 # L2/3, Potjans2014-cm
  Local i-to-i: &local_ii
    density: 0.14 # L2/3, Potjans2014-cm
  Distal e-to-e: &distal_ee
    <<: *ee
    density: 0.1 # Copied from Thalamus to E1
  Distal e-to-i: &distal_ei
    density: 0.05 # Copied from Thalamus to I1

populations:
  Th0:
    n: 10
    rate: 0
    targets:
      Ex1:
        density: 0.1 # Thalamus to L4e, Potjans2014-cm T5
      In1:
        density: 0.05 # Thalamus to L4i, Potjans2014-cm T5
  Ex1:
    <<: *exc
    targets:
      Ex1: *local_ee
      In1: *local_ei
      Ex2: *distal_ee
      In2: *distal_ei
  In1:
    <<: *inh
    targets:
      Ex1: *local_ie
      In1: *local_ii
  Ex2:
    <<: *exc
    targets:
      Ex1: *distal_ee
      In1: *distal_ei
      Ex2: *local_ee
      In2: *local_ei
      Ex3: *distal_ee
      In3: *distal_ei
  In2:
    <<: *inh
    targets:
      Ex2: *local_ie
      In2: *local_ii
  Ex3:
    <<: *exc
    targets:
      Ex2: *distal_ee
      In2: *distal_ei
      Ex3: *local_ee
      In3: *local_ei
  In3:
    <<: *inh
    targets:
      Ex3: *local_ie
      In3: *local_ii
