input:
  n_channels: 1
  populations:
    NAME:
      n: 1
      channel: 0
      targets: # Keyed as AREA.POPULATION
        NAME: &projection
          spatial: False        # Cf. init.py:build_connectivity()
          density: 1.0          # Projection density [0..1]
          sigma: 0.5            # Spatial only: Gaussian kernel radius
          STDP_frac: 0.0        # Fraction of weight ampl under STDP control
          A_p: 0.0              # STDP LTP amplitude
          A_d: 0.0              # STDP LTD amplitude
          wmax: 1.              # Weight limit
NAME:
  tau_mem: 20e-3          # Membrane time constant [s]
  tau_mem_gamma: 3        # >0: Membrane time constant gamma shape parameter
  tau_ref: 5e-3           # Refractory period [s]
  tau_x: 12e-3            # STDP presynaptic time constant (Clopath only) [s]
  tau_p: 30e-3            # STDP potentiation time constant [s]
  tau_d: 10e-3            # STDP depression time constant [s]
  populations:            # Key: Population name [string]
    NAME:
      n: 1                    # Population size
      sign: 1                 # 1: excitatory; -1: inhibitory
      p: 0.0                  # STP amplitude (presynaptic)
      tau_r: 100e-3           # STP recovery time constant [s]
      th_ampl: 0.0            # Amplitude of threshold adaptation
      th_tau: 1.0             # Recovery time constant of threshold adaptation [s]
      noise_N: 0              # Number of poisson noise input sources per neuron
      noise_rate: 0.0         # [Hz] Mean firing rate of noise inputs
      noise_weight: 0.0       # Noise input weight
      targets:                # Keyed as AREA.POPULATION for cross-area,
        NAME:                 # POPULATION for internal projections
          <<: *projection
          delay: 0.0          # Conduction delay [s]
