base:
  time_step: 1e-3         # Integration time step [s]
  n_steps: 100            # Number of integration steps in inner loop
  batch_size: 32
  n_inputs: 20
  n_outputs: 1
  tspec: {}
  model: {}               # Or specify `model_config` with a file path
  train: {}               # Or specify `train_config` with a file path

tspec:
  device: 'cuda:0'
  dtype: 'float'          # torch.dtypes only

model:
  weight_scale: 10.0
  tau_mem: 20e-3          # Membrane time constant [s]
  tau_mem_out: 5e-3       # Readout membrane time constant [s]
  tau_r: 100e-3           # Short-term plasticity recovery time constant [s]
  tau_x: 12e-3            # STDP presynaptic time constant
  tau_p: 30e-3            # STDP potentiation time constant
  tau_d: 10e-3            # STDP depression time constant
  stdp_wmin: 0.0          # STDP minimum weight factor
  stdp_wmax: 2.0          # STDP maximum weight factor
  populations:            # Keyed by population name
    name: {}

population:
  n: 1                    # Population size
  sign: 1                 # 1: excitatory; -1: inhibitory
  p: 0.0                  # Short-term plasticity factor (presynaptic)
  targets:                # Keyed by population name
    name: {}

target:
  density: 1.0            # Projection density [0..1]
  delay: 0.0              # Conduction delay [s]
  A_p: 0.0                # STDP LTP amplitude
  A_d: 0.0                # STDP LTD amplitude
