_prototypes: # Some useful defaults
  Excitatory neuron: &exc
    sign: 1
    p: -0.1                   # Short-term plasticity coefficient
  Inhibitory neuron: &inh
    sign: -1
    p: 0

weight_scale: 10

tau_mem: 20e-3                # Membrane time constant
tau_mem_out: 20e-3            # Readout membrane tau

tau_p: 100e-3                 # Short-term plasticity recovery

populations:
  Exc1:
    <<: *exc
    n: 75
    targets:
      Exc1:
        density: 0.5
      Inh1:
        density: 0.5
  Inh1:
    <<: *inh
    n: 25
    targets:
      Exc1:
        density: 0.5
      Inh1:
        density: 0.5
